version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"

  # Maintain dependencies for terraform
  - package-ecosystem: "terraform"
    directory: "/tentwentyone"
    schedule:
      interval: "weekly"
      day: "thursday"


  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"